"area:frontend":
  - any: ["client/**"]
  - all: ["!client/cypress"]

"area:backend":
  - any: ["server/**"]
  - all: ["!server/cypress"]


"area:api":
  - "server/routes/**"
  - "server/controllers/**"
  - "server/models/**"

test:
- src/**/*.test.js

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
- any: ['src/**/*']

frontend:
- any: ['src/**/*.js']
  all: ['!src/logo.svg']
